apiVersion: batch/v1
kind: Job
metadata:
  name: add-admin
spec:
  template:
    spec:
      containers:
        - name: add-admin
          image: egdocker1/laravel-app:latest
          command: ["php", "artisan", "db:seed", "--class=AdminsTableSeeder"]
          env:
            - name: APP_ENV
              value: "local"
            - name: APP_DEBUG
              value: "true"
            - name: APP_KEY
              value: "base64:your_app_key"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "laravel"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
      restartPolicy: OnFailure
