services:
  ws-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ws_notification_server
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "${WS_PORT:-55333}:8080"
    volumes:
      - ./server:/app:delegated
      - ws_node_modules:/app/node_modules
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  ws_node_modules: