services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Host:Container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Optional override
    restart: unless-stopped
