services:
  webserver:
    image: nginx:alpine
    container_name: chat_microservice_webserver
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:                                  # ← single volumes list
      - ./:/var/www                      # code read-only
      - laravel_storage:/var/www/storage:ro   # uploaded files (read-only for nginx)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - test
      - shared

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_microservice_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www                    
      - vendor_data:/var/www/vendor 
      - laravel_storage:/var/www/storage  # writable volume
      - laravel_cache:/var/www/bootstrap/cache
      

    env_file:
      - .env
    depends_on:
      - mysql-db
    networks:
      - test
      - shared

  mysql-db:
    image: mysql:5.7
    container_name: chat_microservice_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3406:3306"
    networks:
      - test

  redis:
    image: redis:alpine
    container_name: redis2
    restart: unless-stopped
    ports:
      - "6579:6379"          # host 6579 → container 6379
    networks:
      - test
      - shared

networks:
  test:
    driver: bridge
  shared:
    external: true

volumes:
  laravel_storage:
  laravel_cache:
  vendor_data: 
