services:
  api-gateway:
    image: nginx:alpine
    container_name: api_gateway
    restart: unless-stopped
    ports:
      - '8085:80' 
    networks:
      - shared
    volumes:
      # Montamos o ficheiro de configuração para dentro do contêiner.
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  shared:
    external: true
